version: "3"
services:
  static-host:
    build: ./static-host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./http-cache:/http-cache"
    restart: always
  monitor:
    image: docker.umami.dev/umami-software/umami:mysql-latest
    environment:
      - DATABASE_URL=mysql://harry:secret@db:3306/web_data
    ports:
      - "3000:3000"
    restart: always
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=Dk328&!Ir&Ae
      - MYSQL_DATABASE=web_data
      - MYSQL_USER=harry
      - MYSQL_PASSWORD=secret
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    restart: always
  blog:
    build: https://github.com/hbod8/blog.git#main
    ports: 
      - "8080:80"
    restart: always