version: "3"
services:
  static-host:
    image: nginx
    networks:
      - widenet
      - localnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./content:/var/www"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certs:/etc/nginx/certs"
    restart: always
  search:
    image: opensearchproject/opensearch
    networks:
      - localnet
    expose:
      - "9200"
      - "9600"
    volumes:
      - "./search-data:/usr/share/opensearch/data"
    environment:
      - cluster.name=search-cluster
      - node.name=search
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    restart: always
  search-dashboard:
    image: opensearchproject/opensearch-dashboards
    networks:
      - localnet
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    restart: always
networks:
  widenet:
    driver: bridge
  localnet:
    driver: bridge