version: "3"
services:
  static-host:
    build: ./static-host
    networks:
      - widenet
      - localnet
    ports:
      - "80:80"
      - "443:443"
    restart: always
  api:
    build: ./api
    environment:
      - DB_USERNAME=harry
      - DB_PASSWORD=secret
      - DB_HOSTNAME=db
      - DB_PORT=27017
      - DB_NAME=harry
      - JWT_SECRET=secret
      - HTTPS_PORT=8080
      - HTTP_PORT=8081
      - SCRIPT_CALLBACK_URL=http://localhost:8080/data
    networks:
      - localnet
      - widenet
    ports:
      - "8080:8080"
    restart: always
  db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harry
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=harry
    image: mongo
    networks:
      - localnet
    ports:
      - "27107:27107"
    volumes:
      - "./db:/data/db"
networks:
  localnet:
    driver: bridge
  widenet:
    driver: bridge