version: "3"
services:
  static-host:
    build: ./static-host
    ports:
      - "80:80"
      - "127.0.0.1:443:443"
    restart: always
  monitor:
    image: docker.umami.dev/umami-software/umami:mysql-latest
    environment:
      - DATABASE_URL=mysql://harry:secret@db:3306/web_data
    ports:
      - "3000:3000"
    volumes:
      - "./monitor:/var/www/html"
    restart: always
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=Dk328&!Ir&Ae
      - MYSQL_DATABASE=web_data
      - MYSQL_USER=harry
      - MYSQL_PASSWORD=secret
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    restart: always